name: Deploy PowerShell Azure Function App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Azure using SPN
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        auth-type: SERVICE_PRINCIPAL    

    - name: Zip the Azure Function code
      run: |
        cd Functions
        zip -r ../Functions.zip ./*
        cd ..

    - name: Deploy to Azure Function App via ZIP
      run: |
        az functionapp deployment source config-zip \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ secrets.FUNCTION_APP_NAME }} \
          --src Functions.zip
